# Generated by Django 3.0.3 on 2020-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Option Text'),
        ),
    ]
