# Generated by Django 3.0.3 on 2020-08-30 16:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200828_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
